# Generated by Django 6.0.6 on 2026-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0006_incometaxappeal_officer_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestaxappeal',
            name='passing_officer_designation',
            field=models.CharField(blank=True, help_text='Rank of the officer who passed the order, e.g. IRO, ACIR, DCIR, Addl. CIR. Most Sales Tax orders name the post rather than the person, so the name above may be empty while this is filled.', max_length=60, verbose_name='Passing Officer Designation'),
        ),
    ]
